.TH RANDPASS 1 29 March 2013
.SH NAME
randpass - generate a random password
.SH SYNOPSIS
.B randpass [-a]
.SH AVAILABILITY
Mac OSX
.SH DESCRIPTION
randpass generates a string of characters that are suitable for use as passwords. By default, passwords are generated using letters,
symbols and numbers.
.SH OPTIONS
.TP 5
-n
Generate a password using only alpha-numeric characters.
.TP 5
-v
Display the version number
.TP 5
-h
Display usage
.TP 5
-n
.I char-num
Specify the length of the password
.SH AUTHOR
David Griffiths
